import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Course, Chapter } from "@/types/learning";

const mockCourses: Course[] = [
  {
    id: "course-1",
    name: "货币金融学",
    description: "系统学习货币供求、利率机制、通货膨胀与货币政策等核心理论",
    category: "金融学基础",
    chapterCount: 4,
    totalQuestions: 45,
    estimatedHours: 32,
    icon: "Banknote",
  },
  {
    id: "course-2",
    name: "公司金融",
    description: "掌握资本预算、资本结构、股利政策等公司理财核心知识",
    category: "金融学基础",
    chapterCount: 5,
    totalQuestions: 55,
    estimatedHours: 40,
    icon: "Building2",
  },
  {
    id: "course-3",
    name: "投资学",
    description: "学习投资组合理论、资产定价模型、有效市场假说等投资理论",
    category: "投资分析",
    chapterCount: 4,
    totalQuestions: 50,
    estimatedHours: 36,
    icon: "TrendingUp",
  },
  {
    id: "course-4",
    name: "金融市场学",
    description: "深入了解货币市场、资本市场、衍生品市场的运行机制",
    category: "市场分析",
    chapterCount: 4,
    totalQuestions: 48,
    estimatedHours: 34,
    icon: "BarChart3",
  },
  {
    id: "course-5",
    name: "商业银行经营学",
    description: "学习商业银行的业务经营、风险管理、资产负债管理等实务知识",
    category: "银行管理",
    chapterCount: 3,
    totalQuestions: 35,
    estimatedHours: 24,
    icon: "Landmark",
  },
  {
    id: "course-6",
    name: "中央银行学",
    description: "理解中央银行的职能、货币政策工具与宏观调控机制",
    category: "宏观金融",
    chapterCount: 3,
    totalQuestions: 30,
    estimatedHours: 22,
    icon: "Shield",
  },
  {
    id: "course-7",
    name: "证券投资分析",
    description: "掌握基本面分析、技术分析方法及证券估值技术",
    category: "投资分析",
    chapterCount: 5,
    totalQuestions: 60,
    estimatedHours: 42,
    icon: "LineChart",
  },
  {
    id: "course-8",
    name: "国际金融",
    description: "学习国际收支、外汇市场、汇率决定理论及国际货币体系",
    category: "国际金融",
    chapterCount: 4,
    totalQuestions: 42,
    estimatedHours: 30,
    icon: "Globe",
  },
  {
    id: "course-9",
    name: "金融风险管理",
    description: "掌握信用风险、市场风险、操作风险的识别、度量与管理",
    category: "风险管理",
    chapterCount: 4,
    totalQuestions: 46,
    estimatedHours: 35,
    icon: "ShieldAlert",
  },
  {
    id: "course-10",
    name: "431金融综合",
    description: "金融专硕入学考试综合复习，覆盖所有核心考点",
    category: "考研辅导",
    chapterCount: 5,
    totalQuestions: 80,
    estimatedHours: 60,
    icon: "GraduationCap",
  },
];

const mockChapters: Chapter[] = [
  // 货币金融学
  {
    id: "ch-1-1",
    courseId: "course-1",
    title: "货币与货币制度",
    index: 1,
    description: "货币的职能、货币层次划分、货币制度演变",
    keyPoints: ["货币职能", "货币层次", "货币制度", "信用货币", "电子货币"],
    questionCount: 12,
    estimatedMinutes: 45,
  },
  {
    id: "ch-1-2",
    courseId: "course-1",
    title: "信用与利率",
    index: 2,
    description: "信用的形式、利率决定理论、利率结构",
    keyPoints: [
      "信用形式",
      "利率决定",
      "利率期限结构",
      "名义利率与实际利率",
      "费雪方程",
    ],
    questionCount: 11,
    estimatedMinutes: 50,
  },
  {
    id: "ch-1-3",
    courseId: "course-1",
    title: "货币供求与均衡",
    index: 3,
    description: "货币需求理论、货币供给机制、货币均衡与失衡",
    keyPoints: [
      "凯恩斯货币需求",
      "弗里德曼货币需求",
      "货币乘数",
      "基础货币",
      "货币均衡",
    ],
    questionCount: 12,
    estimatedMinutes: 55,
  },
  {
    id: "ch-1-4",
    courseId: "course-1",
    title: "通货膨胀与货币政策",
    index: 4,
    description: "通货膨胀的成因与治理、货币政策目标与工具",
    keyPoints: [
      "通胀成因",
      "菲利普斯曲线",
      "货币政策目标",
      "三大工具",
      "泰勒规则",
    ],
    questionCount: 10,
    estimatedMinutes: 50,
  },
  // 公司金融
  {
    id: "ch-2-1",
    courseId: "course-2",
    title: "财务报表分析",
    index: 1,
    description: "资产负债表、利润表、现金流量表的分析方法",
    keyPoints: [
      "资产负债表",
      "利润表",
      "现金流量表",
      "财务比率分析",
      "杜邦分析",
    ],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-2-2",
    courseId: "course-2",
    title: "货币时间价值",
    index: 2,
    description: "现值、终值、年金、贴现等核心概念与计算",
    keyPoints: ["现值终值", "年金计算", "复利与单利", "贴现率", "净现值"],
    questionCount: 11,
    estimatedMinutes: 45,
  },
  {
    id: "ch-2-3",
    courseId: "course-2",
    title: "资本预算",
    index: 3,
    description: "NPV、IRR、回收期等投资决策方法",
    keyPoints: ["净现值法", "内部收益率", "回收期法", "盈利指数", "互斥项目"],
    questionCount: 12,
    estimatedMinutes: 55,
  },
  {
    id: "ch-2-4",
    courseId: "course-2",
    title: "资本结构与融资决策",
    index: 4,
    description: "MM理论、权衡理论、优序融资理论",
    keyPoints: ["MM定理", "权衡理论", "优序融资", "WACC", "杠杆效应"],
    questionCount: 10,
    estimatedMinutes: 50,
  },
  {
    id: "ch-2-5",
    courseId: "course-2",
    title: "股利政策",
    index: 5,
    description: "股利理论、股利分配方式、股票回购",
    keyPoints: [
      "股利无关论",
      "股利相关论",
      "股票分割",
      "股票回购",
      "股利政策类型",
    ],
    questionCount: 10,
    estimatedMinutes: 40,
  },
  // 投资学
  {
    id: "ch-3-1",
    courseId: "course-3",
    title: "投资组合理论",
    index: 1,
    description: "马科维茨均值-方差模型、有效前沿",
    keyPoints: [
      "均值方差分析",
      "有效前沿",
      "最优投资组合",
      "分散化",
      "协方差矩阵",
    ],
    questionCount: 13,
    estimatedMinutes: 55,
  },
  {
    id: "ch-3-2",
    courseId: "course-3",
    title: "资本资产定价模型",
    index: 2,
    description: "CAPM模型、Beta系数、证券市场线",
    keyPoints: [
      "CAPM公式",
      "Beta系数",
      "证券市场线",
      "市场风险溢价",
      "系统风险",
    ],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-3-3",
    courseId: "course-3",
    title: "套利定价理论",
    index: 3,
    description: "APT模型、多因素模型、套利交易策略",
    keyPoints: [
      "APT模型",
      "多因素模型",
      "套利交易",
      "因素敏感性",
      "与CAPM比较",
    ],
    questionCount: 13,
    estimatedMinutes: 50,
  },
  {
    id: "ch-3-4",
    courseId: "course-3",
    title: "有效市场假说",
    index: 4,
    description: "EMH三种形式、行为金融学挑战",
    keyPoints: ["弱式有效", "半强式有效", "强式有效", "异象", "行为金融"],
    questionCount: 12,
    estimatedMinutes: 45,
  },
  // 金融市场学
  {
    id: "ch-4-1",
    courseId: "course-4",
    title: "货币市场",
    index: 1,
    description: "同业拆借、票据市场、回购市场等",
    keyPoints: ["同业拆借", "商业票据", "银行承兑汇票", "回购协议", "大额存单"],
    questionCount: 12,
    estimatedMinutes: 45,
  },
  {
    id: "ch-4-2",
    courseId: "course-4",
    title: "资本市场",
    index: 2,
    description: "股票市场、债券市场、基金市场的运行机制",
    keyPoints: ["股票发行", "债券定价", "基金分类", "交易所", "做市商"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-4-3",
    courseId: "course-4",
    title: "衍生品市场",
    index: 3,
    description: "期货、期权、互换等金融衍生工具",
    keyPoints: ["期货合约", "期权定价", "互换协议", "远期合约", "衍生品定价"],
    questionCount: 13,
    estimatedMinutes: 55,
  },
  {
    id: "ch-4-4",
    courseId: "course-4",
    title: "金融市场监管",
    index: 4,
    description: "监管体系、信息披露、投资者保护",
    keyPoints: ["监管体系", "信息披露", "投资者保护", "内幕交易", "监管改革"],
    questionCount: 11,
    estimatedMinutes: 40,
  },
  // 商业银行经营学
  {
    id: "ch-5-1",
    courseId: "course-5",
    title: "商业银行概述",
    index: 1,
    description: "商业银行的职能、组织形式与业务分类",
    keyPoints: ["银行职能", "组织形式", "业务分类", "银行制度", "混业经营"],
    questionCount: 12,
    estimatedMinutes: 45,
  },
  {
    id: "ch-5-2",
    courseId: "course-5",
    title: "资产业务与负债业务",
    index: 2,
    description: "贷款业务、投资业务、存款业务等",
    keyPoints: ["贷款分类", "贷款定价", "存款业务", "借款业务", "流动性管理"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-5-3",
    courseId: "course-5",
    title: "银行风险管理",
    index: 3,
    description: "信用风险、流动性风险、利率风险管理",
    keyPoints: [
      "信用风险",
      "流动性风险",
      "利率风险",
      "资本充足率",
      "巴塞尔协议",
    ],
    questionCount: 11,
    estimatedMinutes: 50,
  },
  // 中央银行学
  {
    id: "ch-6-1",
    courseId: "course-6",
    title: "中央银行制度",
    index: 1,
    description: "中央银行的产生、发展与组织形式",
    keyPoints: ["央行职能", "独立性", "组织结构", "央行类型", "中国人民银行"],
    questionCount: 10,
    estimatedMinutes: 40,
  },
  {
    id: "ch-6-2",
    courseId: "course-6",
    title: "货币政策工具",
    index: 2,
    description: "公开市场操作、存款准备金、再贴现等",
    keyPoints: ["公开市场操作", "存款准备金", "再贴现", "创新工具", "政策传导"],
    questionCount: 10,
    estimatedMinutes: 45,
  },
  {
    id: "ch-6-3",
    courseId: "course-6",
    title: "宏观调控与金融稳定",
    index: 3,
    description: "货币政策与财政政策配合、金融稳定框架",
    keyPoints: [
      "政策配合",
      "宏观审慎",
      "金融稳定",
      "最后贷款人",
      "宏观调控效果",
    ],
    questionCount: 10,
    estimatedMinutes: 45,
  },
  // 证券投资分析
  {
    id: "ch-7-1",
    courseId: "course-7",
    title: "基本面分析",
    index: 1,
    description: "宏观经济分析、行业分析、公司分析",
    keyPoints: ["宏观经济分析", "行业分析", "公司分析", "财务分析", "估值方法"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-7-2",
    courseId: "course-7",
    title: "技术分析",
    index: 2,
    description: "K线理论、趋势分析、技术指标",
    keyPoints: ["K线形态", "趋势线", "支撑阻力", "MACD", "RSI指标"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-7-3",
    courseId: "course-7",
    title: "股票估值",
    index: 3,
    description: "绝对估值法与相对估值法",
    keyPoints: ["DCF模型", "DDM模型", "PE估值", "PB估值", "PS估值"],
    questionCount: 12,
    estimatedMinutes: 55,
  },
  {
    id: "ch-7-4",
    courseId: "course-7",
    title: "债券分析",
    index: 4,
    description: "债券定价、久期、凸性分析",
    keyPoints: ["债券定价", "久期", "凸性", "收益率曲线", "信用评级"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  {
    id: "ch-7-5",
    courseId: "course-7",
    title: "投资组合管理",
    index: 5,
    description: "积极与消极管理策略、业绩评价",
    keyPoints: ["积极管理", "消极管理", "业绩评价", "夏普比率", "信息比率"],
    questionCount: 12,
    estimatedMinutes: 50,
  },
  // 国际金融
  {
    id: "ch-8-1",
    courseId: "course-8",
    title: "国际收支",
    index: 1,
    description: "国际收支平衡表、调节理论",
    keyPoints: [
      "国际收支平衡表",
      "经常账户",
      "资本账户",
      "调节理论",
      "弹性分析法",
    ],
    questionCount: 11,
    estimatedMinutes: 45,
  },
  {
    id: "ch-8-2",
    courseId: "course-8",
    title: "外汇与汇率",
    index: 2,
    description: "外汇市场、汇率决定理论、汇率制度",
    keyPoints: ["外汇市场", "汇率决定", "购买力平价", "利率平价", "汇率制度"],
    questionCount: 11,
    estimatedMinutes: 50,
  },
  {
    id: "ch-8-3",
    courseId: "course-8",
    title: "国际货币体系",
    index: 3,
    description: "布雷顿森林体系、牙买加体系、欧元区",
    keyPoints: ["布雷顿森林", "牙买加体系", "欧元区", "SDR", "货币危机"],
    questionCount: 10,
    estimatedMinutes: 45,
  },
  {
    id: "ch-8-4",
    courseId: "course-8",
    title: "国际资本流动",
    index: 4,
    description: "国际资本流动的类型、影响与管理",
    keyPoints: ["资本流动类型", "外债管理", "FDI", "热钱", "资本管制"],
    questionCount: 10,
    estimatedMinutes: 45,
  },
  // 金融风险管理
  {
    id: "ch-9-1",
    courseId: "course-9",
    title: "风险管理概论",
    index: 1,
    description: "风险的定义、分类与风险管理流程",
    keyPoints: ["风险定义", "风险分类", "管理流程", "风险偏好", "风险文化"],
    questionCount: 12,
    estimatedMinutes: 45,
  },
  {
    id: "ch-9-2",
    courseId: "course-9",
    title: "信用风险管理",
    index: 2,
    description: "信用风险度量、信用衍生品、信用评级",
    keyPoints: ["信用风险度量", "5C分析", "CreditMetrics", "CDS", "信用评级"],
    questionCount: 12,
    estimatedMinutes: 55,
  },
  {
    id: "ch-9-3",
    courseId: "course-9",
    title: "市场风险管理",
    index: 3,
    description: "VaR方法、压力测试、市场风险度量",
    keyPoints: ["VaR方法", "历史模拟", "蒙特卡洛", "压力测试", "回溯测试"],
    questionCount: 12,
    estimatedMinutes: 55,
  },
  {
    id: "ch-9-4",
    courseId: "course-9",
    title: "操作风险与全面风险管理",
    index: 4,
    description: "操作风险识别、巴塞尔协议、全面风险管理框架",
    keyPoints: [
      "操作风险",
      "巴塞尔协议",
      "全面风险管理",
      "风险对冲",
      "合规管理",
    ],
    questionCount: 10,
    estimatedMinutes: 45,
  },
  // 431金融综合
  {
    id: "ch-10-1",
    courseId: "course-10",
    title: "金融学基本概念",
    index: 1,
    description: "金融体系概述、金融工具、金融市场基础",
    keyPoints: ["金融体系", "金融工具", "金融市场", "金融机构", "金融功能"],
    questionCount: 16,
    estimatedMinutes: 60,
  },
  {
    id: "ch-10-2",
    courseId: "course-10",
    title: "公司理财核心",
    index: 2,
    description: "NPV、资本预算、资本结构、股利政策",
    keyPoints: ["NPV法则", "资本预算", "WACC", "MM理论", "股利政策"],
    questionCount: 16,
    estimatedMinutes: 65,
  },
  {
    id: "ch-10-3",
    courseId: "course-10",
    title: "投资学与定价",
    index: 3,
    description: "CAPM、APT、有效市场、衍生品定价",
    keyPoints: ["CAPM", "APT", "EMH", "期权定价", "期货定价"],
    questionCount: 16,
    estimatedMinutes: 65,
  },
  {
    id: "ch-10-4",
    courseId: "course-10",
    title: "货币银行学",
    index: 4,
    description: "货币供求、利率、通货膨胀、货币政策",
    keyPoints: ["货币需求", "货币供给", "利率理论", "通货膨胀", "货币政策"],
    questionCount: 16,
    estimatedMinutes: 60,
  },
  {
    id: "ch-10-5",
    courseId: "course-10",
    title: "国际金融与热点",
    index: 5,
    description: "汇率、国际收支、金融热点问题",
    keyPoints: ["汇率理论", "国际收支", "货币危机", "金融创新", "金融监管"],
    questionCount: 16,
    estimatedMinutes: 60,
  },
];

export interface LearningState {
  courses: Course[];
  selectedCourse: Course | null;
  selectedChapter: Chapter | null;
  chapters: Chapter[];
  searchQuery: string;
  selectCourse: (course: Course | null) => void;
  selectChapter: (chapter: Chapter | null) => void;
  setSearchQuery: (query: string) => void;
}

export const useLearningStore = create<LearningState>()(
  persist(
    (set) => ({
      courses: mockCourses,
      selectedCourse: null,
      selectedChapter: null,
      chapters: mockChapters,
      searchQuery: "",
      selectCourse: (course) =>
        set({ selectedCourse: course, selectedChapter: null }),
      selectChapter: (chapter) => set({ selectedChapter: chapter }),
      setSearchQuery: (query) => set({ searchQuery: query }),
    }),
    {
      name: "finpilot-learning-store",
      partialize: (state) => ({
        selectedCourse: state.selectedCourse,
        selectedChapter: state.selectedChapter,
        searchQuery: state.searchQuery,
      }),
    },
  ),
);
