# -*- coding: utf-8 -*-
"""FinPilot AI Launcher - Dependency Installer"""

import subprocess
import sys
import os
from core.logger import Logger


class Installer:
    """Install frontend and backend dependencies with fallback."""

    def __init__(self, logger: Logger):
        self.logger = logger
        self.project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    @property
    def api_dir(self) -> str:
        return os.path.join(self.project_root, "apps", "api")

    @property
    def web_dir(self) -> str:
        return os.path.join(self.project_root, "apps", "web")

    def _get_venv_python(self) -> str:
        if sys.platform == "win32":
            return os.path.join(self.api_dir, "venv", "Scripts", "python.exe")
        return os.path.join(self.api_dir, "venv", "bin", "python")

    def _get_venv_pip(self) -> str:
        if sys.platform == "win32":
            return os.path.join(self.api_dir, "venv", "Scripts", "pip.exe")
        return os.path.join(self.api_dir, "venv", "bin", "pip")

    def _run(self, cmd: list[str], cwd: str, label: str) -> bool:
        try:
            self.logger.info(f"执行: {' '.join(cmd)}")
            result = subprocess.run(
                cmd, cwd=cwd, capture_output=True, text=True, timeout=300,
                shell=(sys.platform == "win32"),
            )
            if result.returncode == 0:
                return True
            self.logger.warn(f"{label} 返回非零退出码 {result.returncode}")
            return False
        except subprocess.TimeoutExpired:
            self.logger.warn(f"{label} 超时")
            return False
        except Exception as e:
            self.logger.warn(f"{label} 失败: {e}")
            return False

    def create_venv(self) -> bool:
        """Create Python virtual environment if not exists."""
        venv_python = self._get_venv_python()
        if os.path.isfile(venv_python):
            self.logger.success("虚拟环境已存在")
            return True

        self.logger.info("正在创建 Python 虚拟环境...")
        ok = self._run(
            [sys.executable, "-m", "venv", "venv"],
            cwd=self.api_dir, label="venv创建",
        )
        if ok:
            self.logger.success("虚拟环境已创建")
        else:
            self.logger.error("虚拟环境创建失败")
        return ok

    def install_backend(self) -> bool:
        """Install backend dependencies with fallback."""
        req_file = os.path.join(self.api_dir, "requirements.txt")
        venv_pip = self._get_venv_pip()

        # Generate requirements.txt if missing
        if not os.path.isfile(req_file):
            self.logger.warn("requirements.txt 不存在，生成基础依赖")
            default_deps = [
                "fastapi>=0.104.0",
                "uvicorn[standard]>=0.24.0",
                "pydantic>=2.0.0",
                "python-multipart>=0.0.6",
                "requests>=2.31.0",
                "openai>=1.0.0",
                "chromadb>=0.4.0",
                "akshare>=1.12.0",
                "python-dotenv>=1.0.0",
                "aiofiles>=23.0.0",
                "aiosqlite>=0.19.0",
                "alembic>=1.13.0",
                "sqlalchemy>=2.0.0",
            ]
            with open(req_file, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by FinPilot Launcher\n")
                f.write("\n".join(default_deps))
            self.logger.success("已生成基础 requirements.txt")

        # Try with venv pip first
        if os.path.isfile(venv_pip):
            ok = self._run(
                [venv_pip, "install", "-r", "requirements.txt", "-q"],
                cwd=self.api_dir, label="pip install",
            )
            if ok:
                self.logger.success("后端依赖安装完成")
                return True

        # Fallback: system pip
        self.logger.warn("venv pip 安装失败，尝试系统 pip...")
        ok = self._run(
            ["pip", "install", "-r", "requirements.txt", "-q"],
            cwd=self.api_dir, label="pip install (system)",
        )
        if ok:
            self.logger.success("后端依赖安装完成（使用系统 pip）")
            return True

        self.logger.error("后端依赖安装失败")
        return False

    def install_frontend(self) -> bool:
        """Install frontend dependencies with fallback."""
        node_modules = os.path.join(self.web_dir, "node_modules")
        if os.path.isdir(node_modules):
            self.logger.success("前端依赖已安装")
            return True

        # Standard install
        ok = self._run(
            ["npm", "install"],
            cwd=self.web_dir, label="npm install",
        )
        if ok:
            self.logger.success("前端依赖安装完成")
            return True

        # Fallback: legacy-peer-deps
        self.logger.warn("npm install 失败，尝试 --legacy-peer-deps...")
        ok = self._run(
            ["npm", "install", "--legacy-peer-deps"],
            cwd=self.web_dir, label="npm install --legacy-peer-deps",
        )
        if ok:
            self.logger.success("前端依赖安装完成（legacy-peer-deps）")
            return True

        self.logger.error("前端依赖安装失败")
        return False
